version: '3.1'

services:

  psql-compose:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./bot_db:/var/lib/postgresql/data
