DELETE
FROM english_quiz;

INSERT INTO english_quiz (question, answer_correct, option1, option2, option3)
VALUES ('1. My favorite color _____ green.', 'is', 'be', 'are', 'am'),
--        ('', '', '', '', ''),
       ('2. We get up _____ 7 o’clock.', 'at', 'in', 'of', 'on'),
       ('3. There is _____ milk in the fridge.', 'some', 'a', 'the', '-'),
       ('4. Are you _____ Italy?', 'from', 'of', 'at', 'out'),
       ('5. London is the _____ of England.', 'capital', 'symbol', 'country', '-'),
       ('6. Last Sunday I _____ football with my friends.', 'played', 'play', 'plays', 'playing'),
       ('7. This is _____ film I have ever seen.', 'the best', 'good', 'better', 'well'),
       ('8. _____ I have a ticket to London?', 'can', 'do', 'should', 'will'),
       ('9. How _____ friends do you have?', 'many', 'often', 'much', 'long'),
       ('10. Excuse me, _____ my hat.', 'that is', 'those is', 'that are', 'those are'),
       ('11. _____ elephants are very beautiful animals.', '—', 'The', 'A', 'An'),
       ('12. How about going to the cinema? _____ ', 'Sounds good. What’s on?', 'See you there', 'Not a problem',
        'Nice to meet you'),
       ('13. She is a woman _____ helped me with a job.', 'who', 'which', 'whose', 'where'),
       ('14. They _____ me they would come the next day.', 'told', 'said', 'spoke', 'talked'),
       ('15. I hate _____ up early in the morning.', 'getting', 'get', 'got', 'gotten'),
       ('16. If I were you, I _____ buy this car.', 'would', 'will', 'should', 'can'),
       ('17. He didn’t go to school, _____ ', 'although he wasn’t ill', 'so he was ill', 'because he was there',
        'but is here'),
       ('18. It’s not a good idea to leave electrical appliance _____ standby.', 'on', 'for', 'at', 'in'),
       ('19. When I want to relax I put my feet _____ ', 'up', 'on', 'down', 'off'),
       ('20. They are usually punished for _____ a teacher.', 'disobeying', 'obey', 'disobey', 'obeying'),
       ('21. I _____ her since we were teenagers.', 'have known', 'know', 'knew', 'have been knowing'),
       ('22. _____ we came, train had already departed.', 'By the time', 'When', 'Until', 'As soon as'),
       ('23. I remember _____ him at work and he was tired.', 'seeing', 'to see', 'see', 'saw'),
       ('24. You _____ Jack in the gym, because he had gone to France.', 'can’t have seen', 'couldn’t see',
        'can’t see', 'haven’t seen'),
       ('25. I was frustrated at not having news _____ the interview I had had before.', 'regarding', 'relates',
        'comparing with', 'in order to');